#
# Cleans up a GitHub PR
#
name: 🧼 Clean up environment
on:
pull_request:
  types:
    - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      # Points to a recent commit instead of `main` to avoid supply chain attacks. (The latest tag is very old.)
      - name: 🎟 Get GitHub App token
        uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1
        id: get-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: 🗑 Delete deployment environment
        uses: strumwolf/delete-deployment-environment@v2.2.3
        with:
          # Use a JWT created with your GitHub App's private key
          token: ${{ steps.get-token.outputs.token }}
          environment: pr-${{ github.event.number }}
          ref: ${{ github.ref_name }}


          name: Delete Deployments

on:
  delete:
    branches-ignore:
      - main

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: my-environment-name
          onlyRemoveDeployments: true
