name: Cleanup Deployments

on: 
  delete:
  workflow_dispatch: # Allows you to click the "Run" button manually

jobs:
  delete-env:
    # This prevents the script from accidentally nuking your live master site
    if: github.event.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    
    # 1. FIXES "Resource not accessible"
    permissions:
      deployments: write
      contents: read

    env:
      # 2. SILENCES the Deprecation Warning
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Delete Deployment
        # 3. UPDATED to v3 for Node 24 support
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
