name: Cleanup Deployments

on: 
  delete:
  workflow_dispatch:

jobs:
  delete-env:
    # This 'if' check replaces 'branches-ignore' 
    # It ensures the job only runs if the deleted branch WAS NOT master
    if: github.event.ref != 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Delete Deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
