name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  delete:
    branches-ignore:
    - master

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        run: npm install --global pnpm

      - name: Install deps
        run: pnpm install

      - name: Build plugin(s)
        run: node ./build.mjs

      - name: Copy additional files
        run: |
          cp README.md dist/README.md
          printf -- "---\npermalink: /404.html\n---\n" > dist/404.md
          printf -- "> **Note:** You accessed a link that returned a 404.\n\n" >> dist/404.md
          cat README.md >> dist/404.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: true

  delete-deployments:
    if: github.event_name == 'delete'
    runs-on: ubuntu-latest
    steps:
      - name: Delete Deployment Environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
